workflows:
  android-release:
    name: Android Release APK
    max_build_duration: 60

    environment:
      vars:
        PACKAGE_NAME: "com.avarias.danosaparentes"

    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - seuemail@gmail.com
